import { useState } from "react";

import { getRandomQuote } from "../utils/quotesApi.js";

import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import AppBar from "@mui/material/AppBar";
import Box from "@mui/material/Box";
import Button from "@mui/material/Button";

import Container from "@mui/material/Container";

import Toolbar from "@mui/material/Toolbar";
import Typography from "@mui/material/Typography";

export default function Home() {
  // let's pretend we have some data that is scoped externally from the web.
  // just like incoming REST API would be.
  // const newData = { quote: "You can't just make up quotes", author: "Oscar Wilde" };

  const [quoteData, setQuoteData] = useState({
    quote: "Quote here.",
    author: "Author here",
  });

  const getQuote = () => {
    const quoteData = getRandomQuote();
    setQuoteData({
      quote: quoteData.quote,
      author: quoteData.author,
    });
  };

  return (
    <div>
      <Head>
        <title>We Love Quotes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBar position="relative">
        <Toolbar>
          <Typography variant="h6" color="inherit" noWrap>
            We Love Quotes
          </Typography>
        </Toolbar>
      </AppBar>
      <main>
        <Container maxWidth="sm">
          <Box
            sx={{
              bgcolor: "background.paper",
              pt: 8,
              pb: 6,
            }}
          >
            <Typography variant="h5" align="center" color="text.primary" paragraph>
              {quoteData.quote}
            </Typography>
            <Typography component="h1" variant="h4" align="center" color="text.secondary" gutterBottom>
              {quoteData.author}
            </Typography>
            <Box display="flex" justifyContent="center">
              <Button variant="contained" onClick={getRandomQuote}>
                Get New Quote
              </Button>
            </Box>
          </Box>
        </Container>
      </main>
    </div>
  );
}
