import Head from "next/head";

// MUI components
import Container from "@mui/material/Container";
import Box from "@mui/material/Box";

export default function Home() {
  return (
    <>
      <Head>
        <title>MUI intro</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main>
          <Container maxWidth="md" style={{ background: "#cccccc" }}>
            <Box sx={{ my: 4 }}>some content we'll add later</Box>
          </Container>
        </main>
      </div>
    </>
  );
}
